### ISSUE TITLE
not booting on RPI 3 B+

### ISSUE THREAD

**Issue by loki-sft** [kerberos-io/kios#30]
I hava a running Instance based on Raspbian without any issue.
Then I wanted to try out the KIOS version but the rpi is not booting. Red LED is just flashing.

I had the same issue when I switched from the rpi 3b to 3b+ with noobs image without upgrading.

**Comment by cedricve** [comment]
I'll check what kernel we need to use. Thanks for reporting.

**Comment by ghost** [comment]
Any updates? Same issue here.

**Comment by cedricve** [comment]
can someone test this pre-release: https://github.com/cedricve/kios/releases/download/develop/kios-raspberrypi3-20180519.img.gz

This includes support for 3B+.

**Comment by ghost** [comment]
Thank you, will try when I get home!

**Comment by cedricve** [comment]
@acvigue keep me posted if this worked for you.

**Comment by Polodu13** [comment]
Dear Cedric, I tested the version https://github.com/cedricve/kios/releases/download/develop/kios-raspberrypi3-20180521.img.gz. It's working on my Pi3  but not on Pi 3B+. I can't download the pre release:
https://github.com/cedricve/kios/releases/download/develop/kios-raspberrypi3-20180519.img.gz

**Comment by ghost** [comment]
It boots and works for me

**Comment by Polodu13** [comment]
Acvigue, which version or which path to download?

**Comment by ghost** [comment]
Excuse that message, I had multiple GitHub issues in my inbox and replied to the wrong one. I actually get a 404 error when downloading the prerelease that you linked.(20180519)

**Comment by cedricve** [comment]
@acvigue not sure what your final conclusion is? Does it work?

**Comment by ghost** [comment]
No I could not download the link you sent. It gave a 404 not found error.

**Comment by cedricve** [comment]
Please find it here: https://github.com/cedricve/kios/releases/tag/develop

**Comment by Polodu13** [comment]
Hello, I just tried with https://github.com/cedricve/kios/releases/download/develop/kios-raspberrypi3-20180523.img.gz but it's not working on my Pi.

**Comment by cedricve** [comment]
ok thanks for testing.

**Comment by cedricve** [comment]
@Polodu13  can you try again, there is a new image available. Thanks!

**Comment by Polodu13** [comment]
Salut Cédric,
It's not booting on my pi 3B+. It's booting & working on Pi 3B...

**Comment by cedricve** [comment]
you used the 24/05 image?

**Comment by cedricve** [comment]
Hmm indeed something was missing, I'm recompiling the image again. Keep you posted.

**Comment by Polodu13** [comment]
Well noted

**Comment by cedricve** [comment]
Ok @Polodu13, should be ok this time. https://github.com/cedricve/kios/releases
Can you try once more?

**Comment by Polodu13** [comment]
I just tried but it's the same. Booting on pi3b but not on 3b+. I used https://github.com/cedricve/kios/releases/download/develop/kios-raspberrypi3-20180525.img.gz

**Comment by cedricve** [comment]
Hmm looks like the rpi3 image wasn't updated, recompiling it once more. Should be ok after this. I'll drop a message when it's ready.

**Comment by cedricve** [comment]
@Polodu13  ok this time it should be working. Please let me know.

**Comment by Polodu13** [comment]
@cedricve It's booting now. But  I can not configure the WIFI network and I have trouble sharing the stream on port 8889. I sent you the logs on cedric@verstraeten.io

**Comment by cedricve** [comment]
Hmm it looks like it was crashing at the beginning. Can you send me the wpa_*.conf file ? 
Also which browser are you using?

**Comment by Polodu13** [comment]
I'm using firefox. I sent you the wpa_*.conf file to cedric@verstraeten.io

**Comment by cedricve** [comment]
hmm I was able to reproduce, something is missing the new RPI3 missing.

**Comment by cedricve** [comment]
Support for Raspberry Pi 3B+ fixed, however having an issue with wpa_supplicant.
Linked issue: https://github.com/kerberos-io/kios/issues/31.

**Comment by Polodu13** [comment]
@cedricve . FYI i'm not able to change the angle and resolution of pi cam on your last release https://github.com/cedricve/kios/releases/download/develop/kios-raspberrypi3-20180526.img.gz

**Comment by cedricve** [comment]
@Polodu13  can you send me the logs? How did you update the camera settings?

**Comment by Polodu13** [comment]
@cedricve . I change on settings/machinery/advance/captur//frameWidth etc. when I validate but changes are not updated.

**Comment by cedricve** [comment]
@Polodu13 did some more tests and it should be working now (both WIFI and editing config files). Let me know how it goes. Can you also check Pi3B+ support? thanks!!

**Comment by Polodu13** [comment]
@cedricve . Angle and camera resolution are working good. Thanks. For the moment I m not able to use wifi... i continue to check if i need to change the file... what do you mean by  "Can you also check Pi3B+ support"?

**Comment by cedricve** [comment]
Thanks for testign @Polodu13, you are still not able to use WIFI, or you don't know how to configure it?

**Comment by Polodu13** [comment]
Hello, I used the same file as for the pi3 which is working well but it's not working on pi3 b+. I already sent this file to you (wpa_supplicant.conf.txt). Actually, I don't know what to change

**Comment by cedricve** [comment]
Hmm weird, can someone else confirm having issues with the pi3B+?

**Comment by failfailsucceed** [comment]
2.70 boots and I can connect via ethernet  but the pi3B+  onboard wifi device is not recognized.

**Comment by cedricve** [comment]
should be fixed in this release: https://github.com/cedricve/kios/releases/tag/develop.

Can someone try? @Polodu13  @failfailsucceed ?

**Comment by Polodu13** [comment]
@cedricve hello, Wifi is working now but I have trouble sharing the stream on port 8889. I sent you the logs on cedric@verstraeten.io

**Comment by cedricve** [comment]
hey @Polodu13, what is the issue? I see that you're continously restarting the machinery?

**Comment by Polodu13** [comment]
I tried to see the video via ip:8889 on firefox but it's not working. I can see the video few second and after... blackout... I tried to restart the pi, changed cam resolution, I tried via ethernet. It's seem that the video crash after few second. However, I still have access to kerberos tabs

**Comment by cedricve** [comment]
that explains a lot .. Mozilla doesn't support this feature. You should use Chrome.

**Comment by Polodu13** [comment]
Noted, but I downloaded chrome and it's the same. It's working few seconds and after I lost the video. On activity tab it's written: No stream, is machinery running?

**Comment by cedricve** [comment]
Can we do a teamviewer session, I would like to see it.
